import { primitiveTokens } from './primitives';

export const semanticTokens = {
  colors: {
    background: primitiveTokens.palette.canvas,
    foreground: primitiveTokens.palette.ink,
    card: primitiveTokens.palette.surface,
    cardForeground: primitiveTokens.palette.ink,
    popover: primitiveTokens.palette.surface,
    popoverForeground: primitiveTokens.palette.ink,
    primary: primitiveTokens.palette.ink,
    primaryForeground: primitiveTokens.palette.canvas,
    primaryDeep: primitiveTokens.palette.primaryDeep,
    secondary: primitiveTokens.palette.sun,
    secondaryForeground: primitiveTokens.palette.surface,
    muted: primitiveTokens.palette.subtleSurface,
    mutedForeground: primitiveTokens.palette.mutedText,
    accent: primitiveTokens.palette.sky,
    accentForeground: primitiveTokens.palette.surface,
    border: primitiveTokens.palette.line,
    input: primitiveTokens.palette.field,
    ring: primitiveTokens.palette.ink,
    danger: primitiveTokens.palette.danger,
    dangerForeground: primitiveTokens.palette.surface,
    destructive: primitiveTokens.palette.danger,
    destructiveForeground: primitiveTokens.palette.surface,
    trust: primitiveTokens.palette.trust,
    trustForeground: primitiveTokens.palette.surface,
    trustMuted: primitiveTokens.palette.trustMuted,
    statusOpen: primitiveTokens.palette.statusOpen,
    statusOpenForeground: primitiveTokens.palette.statusOpenForeground,
    statusAssigned: primitiveTokens.palette.statusAssigned,
    statusAssignedForeground: primitiveTokens.palette.statusAssignedForeground,
    verified: primitiveTokens.palette.verified,
    verifiedForeground: primitiveTokens.palette.surface,
    subtleViolet: primitiveTokens.palette.subtleSurface,
    chipInactive: primitiveTokens.palette.chipInactive,
    textSecondary: primitiveTokens.palette.textSecondary,
    textTertiary: primitiveTokens.palette.textTertiary,
    navInactive: primitiveTokens.palette.navInactive,
  },
  spacing: {
    xs: primitiveTokens.spacingScale[1],
    sm: primitiveTokens.spacingScale[2],
    md: primitiveTokens.spacingScale[3],
    lg: primitiveTokens.spacingScale[4],
    xl: primitiveTokens.spacingScale[6],
    '2xl': primitiveTokens.spacingScale[8],
    '3xl': primitiveTokens.spacingScale[10],
  },
  radius: {
    xs: primitiveTokens.radiusScale.xs,
    sm: primitiveTokens.radiusScale.sm,
    md: primitiveTokens.radiusScale.md,
    lg: primitiveTokens.radiusScale.lg,
    full: primitiveTokens.radiusScale.full,
  },
  typography: {
    families: primitiveTokens.typography.families,
    weights: primitiveTokens.typography.fontWeights,
    fontSizes: primitiveTokens.typography.fontSizes,
    lineHeights: primitiveTokens.typography.lineHeights,
    letterSpacing: primitiveTokens.typography.letterSpacing,
    minBodySize: primitiveTokens.typography.minBodySize,
  },
  shadows: primitiveTokens.shadows,
} as const;

export type SemanticTokens = typeof semanticTokens;
