import { mobileTheme, withAlpha } from './theme';

const { colors, radius } = mobileTheme;

export const mobileSurfaces = {
  tint: {
    primarySubtle: withAlpha(colors.primary, 0.1),
    primarySoft: withAlpha(colors.primary, 0.12),
    primaryStrong: withAlpha(colors.primary, 0.15),
    primaryForegroundSoft: withAlpha(colors.primaryForeground, 0.1),
    primaryForegroundMuted: withAlpha(colors.primaryForeground, 0.6),
    dangerSoft: withAlpha(colors.danger, 0.08),
    dangerSubtle: withAlpha(colors.danger, 0.1),
    dangerMedium: withAlpha(colors.danger, 0.12),
    trustSoft: withAlpha(colors.trust, 0.13),
    verifiedSoft: withAlpha(colors.verified, 0.1),
    categoryPill: withAlpha(colors.primary, 0.12),
    borderSoft: withAlpha(colors.border, 0.5),
  },
  onboarding: {
    illustrationCard: {
      width: 326,
      height: 407,
      radius: 32,
      rotation: '-3deg',
      iconSize: 24,
      badgeOffset: 24,
    },
    pagination: {
      height: 3,
      activeWidth: 10,
      inactiveWidth: 6,
    },
    skipSpacer: {
      width: 56,
      height: 24,
    },
  },
  otp: {
    contentTopInset: 72,
    contentBottomInset: 32,
    contentGap: 24,
    stickyInset: 96,
    codeCellSize: 48,
    securityIconBox: 36,
    verifyButtonHeight: 56,
    wrongCodeOpacity: 0.96,
    resendDisabledOpacity: 0.8,
    resendPressedOpacity: 0.75,
    descriptionLineHeight: 26,
    errorLineHeight: 20,
    securityLineHeight: 21,
  },
  otpMigration: {
    heroTopInset: 72,
    iconButton: 40,
    heroCard: 96,
    halo: 144,
    headingTracking: -0.6,
    bodyMaxWidth: 320,
    phonePrefixInset: 64,
    submitHeight: 56,
    skipHeight: 44,
  },
  splash: {
    brandSize: 56,
    markBox: 64,
    markRadius: 16,
    markIcon: 24,
    markBorder: withAlpha(colors.primaryForeground, 0.12),
    markSurface: withAlpha(colors.primaryForeground, 0.08),
    progressRailWidth: 136,
    progressRailHeight: 2,
    progressFillWidth: 42,
    progressSurface: withAlpha(colors.primaryForeground, 0.16),
    footerText: withAlpha(colors.primaryForeground, 0.72),
    footerBottom: 64,
    loaderBottom: 28,
  },
  taskDetail: {
    labelTracking: 1.05,
    sectionTracking: 0.9,
    budgetLineHeight: 40,
    pillMinWidth: 28,
    pillInsetX: 8,
    pillInsetY: 4,
    photoTileHeight: 163,
    photoTileWidth: '48%',
  },
  instantMatch: {
    minHeight: 480,
    ringStackHeight: 220,
    ringOuter: 180,
    ringMiddle: 132,
    ringInner: 88,
    ringDot: 14,
  },
  bookingList: {
    railHeight: 1,
    skeletonAvatar: 40,
    skeletonTitleWidth: '72%',
    skeletonSubtitleWidth: '48%',
    skeletonPillWidth: 72,
    skeletonPillHeight: 24,
    skeletonMetaWidth: '42%',
    skeletonPriceWidth: 72,
    skeletonPriceHeight: 16,
    headerIconBox: 40,
    emptyIconBox: 64,
    ctaHeight: 48,
    statusTracking: 0.6,
  },
  permissionPrimer: {
    topIllustrationSize: 128,
    sheetHandleWidth: 40,
    sheetHandleHeight: 4,
    iconPreviewSize: 96,
    badgeOffset: -8,
    badgeSize: 32,
    badgeBorder: 4,
    titleSize: 24,
    titleTracking: -0.5,
    bodyLineHeight: 24,
    hintLineHeight: 20,
    footerLineHeight: 18,
    buttonHeight: 56,
  },
  bookingTimeline: {
    dotSize: 24,
    railWidth: 2,
    railMinHeight: 28,
    railOffset: -1,
    cardIconBox: 64,
    helpCtaHeight: 48,
    titleTracking: 0.8,
  },
  bookingConfirmed: {
    navIconBox: 40,
    heroSize: 96,
    nextStepIconBox: 40,
    providerAvatarBox: 48,
    primaryCtaHeight: 52,
    bottomGlowHeight: 80,
    bottomGlowRadius: 40,
  },
  referrals: {
    heroSize: 24,
    heroLineHeight: 34,
    bodyOpacity: 0.85,
    codeSurface: withAlpha(colors.primaryForeground, 0.08),
    codeTracking: 0.4,
    bonusSurface: withAlpha(colors.secondary, 0.22),
  },
  iconButton: {
    sm: 40,
    md: 42,
    lg: 44,
  },
  artwork: {
    mutedHeroRadius: radius.lg,
  },
  statusHero: {
    iconBox: 72,
  },
  paragraphLineHeight: 24,
  touchTarget: {
    ctaHeight: 48,
  },
} as const;

export type MobileSurfaces = typeof mobileSurfaces;
