import assert from "node:assert/strict";
import { existsSync, readdirSync, readFileSync } from "node:fs";
import path from "node:path";
import test from "node:test";
import YAML from "yaml";
import {
    generatedInventoryPath,
    renderOpsInventory,
} from "../scripts/gates/sync-ops-registry.mjs";

const repoRoot = process.cwd();
const registryPath = path.join(repoRoot, "tooling", "config", "ops-registry.yaml");

function readYaml(filePath) {
    return YAML.parse(readFileSync(filePath, "utf8"));
}

function readRegistry() {
    assert.ok(existsSync(registryPath), "tooling/config/ops-registry.yaml must exist");
    return readYaml(registryPath);
}

function walkToolingScripts(dir) {
    return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
        const fullPath = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            if (entry.name === "__pycache__") {
                return [];
            }
            return walkToolingScripts(fullPath);
        }
        if (![".mjs", ".py", ".sh"].includes(path.extname(entry.name))) {
            return [];
        }
        return [path.relative(path.join(repoRoot, "tooling", "scripts"), fullPath).replaceAll(path.sep, "/")];
    });
}

test("ops registry covers every GitHub workflow and treats ops diagrams as ephemeral", () => {
    const registry = readRegistry();
    const expectedWorkflows = readdirSync(path.join(repoRoot, ".github", "workflows"))
        .filter((file) => file.endsWith(".yml") || file.endsWith(".yaml"))
        .map((file) => `.github/workflows/${file}`)
        .sort();
    const registryWorkflows = Object.keys(registry.workflows ?? {}).sort();

    assert.deepEqual(registryWorkflows, expectedWorkflows);
    assert.equal(registry.policy?.opsDiagrams, "ephemeral");
    assert.ok(!(registry.docs ?? []).includes("docs/ops/diagrams"));
});

test("ops registry classifies every tooling script with an explicit lifecycle", () => {
    const registry = readRegistry();
    const scripts = walkToolingScripts(path.join(repoRoot, "tooling", "scripts")).sort();
    const registryScripts = Object.keys(registry.toolingScripts ?? {}).sort();
    const allowedLifecycles = new Set(["blocking", "called_by_script", "manual", "report_only", "deprecated"]);

    assert.deepEqual(registryScripts, scripts);
    for (const [scriptPath, entry] of Object.entries(registry.toolingScripts ?? {})) {
        assert.ok(allowedLifecycles.has(entry.lifecycle), `${scriptPath} has invalid lifecycle ${entry.lifecycle}`);
    }
});

test("registry package command expectations match package.json exactly", () => {
    const registry = readRegistry();
    const packageJson = JSON.parse(readFileSync(path.join(repoRoot, "package.json"), "utf8"));

    for (const [scriptName, expected] of Object.entries(registry.packageScripts ?? {})) {
        assert.equal(packageJson.scripts?.[scriptName], expected.command, `${scriptName} package script drifted`);
    }
});

test("ops inventory documentation is generated from the registry", () => {
    const registry = readRegistry();
    const expected = renderOpsInventory(registry);
    const inventoryPath = path.join(repoRoot, generatedInventoryPath);

    assert.ok(existsSync(inventoryPath), `${generatedInventoryPath} must exist`);
    assert.equal(readFileSync(inventoryPath, "utf8"), expected);
    assert.match(expected, /Generated by `pnpm repo:ops:sync --fix`/);
    assert.match(expected, /security-review\.yml/);
    assert.match(expected, /`docs\/ops\/diagrams\/\*\*` are ephemeral/);
});
