#!/usr/bin/env bash
# sync-registry.sh
# Parses tests/scenarios/*.md for SCN-* entries, syncs tests/registry.yaml,
# cross-references @DisplayName annotations in test code to update status,
# and parses PIT XML to update mutation_kill_rate per domain.
#
# Usage: ./scripts/sync-registry.sh
# Run from the repository root.
set -euo pipefail

SCENARIOS_DIR="tests/scenarios"
REGISTRY="tests/registry.yaml"
TEST_SRC="src/test/java"
PIT_XML="build/reports/pitest/mutations.xml"

# ── Step 1: Parse scenario files and upsert registry ─────────────────────────
python3 - <<'PYEOF'
import re, sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("[sync] ERROR: pyyaml not installed. Run: pip3 install pyyaml", file=sys.stderr)
    sys.exit(1)

scenarios_dir = Path("tests/scenarios")
registry_path = Path("tests/registry.yaml")

# Load existing registry to preserve notes and override_status
existing = {}
if registry_path.exists():
    with open(registry_path) as f:
        data = yaml.safe_load(f) or {}
        existing = data.get("scenarios") or {}

scenarios = {}

for md_file in sorted(scenarios_dir.glob("*.md")):
    domain = md_file.stem
    if domain == "README":
        continue
    content = md_file.read_text()
    blocks = re.split(r'\n(?=## SCN-)', content)
    for block in blocks:
        m = re.match(
            r'## (SCN-[A-Z]+-\d+)\n\*\*Risk:\*\* (\w+)\n\*\*PRD:\*\* ([^\n]+)\n\*\*Title:\*\* ([^\n]+)',
            block
        )
        if not m:
            continue
        scn_id = m.group(1)
        risk = m.group(2).strip().lower()
        prd_ref = m.group(3).strip()
        title = m.group(4).strip()

        test_type = "domain-unit" if risk in ("critical", "high") else "medium-unit"
        if domain == "integration":
            test_type = "integration"

        prev = existing.get(scn_id) or {}
        scenarios[scn_id] = {
            "title": title,
            "domain": domain,
            "risk": risk,
            "prd_ref": prd_ref,
            "test_type": test_type,
            "status": prev.get("status", "untested"),
            "mutation_kill_rate": prev.get("mutation_kill_rate"),
            "notes": prev.get("notes"),
            "override_status": prev.get("override_status"),
        }

registry_path.parent.mkdir(parents=True, exist_ok=True)
with open(registry_path, "w") as f:
    f.write("# Auto-generated by scripts/sync-registry.sh\n")
    f.write("# Edit scenario entries in tests/scenarios/<domain>.md only.\n")
    f.write("# Hand-edit only: notes, override_status.\n\n")
    yaml.dump({"scenarios": scenarios}, f, default_flow_style=False, sort_keys=True, allow_unicode=True)

print(f"[sync] Parsed {len(scenarios)} scenarios from {scenarios_dir}")
PYEOF

# ── Step 2: Scan @DisplayName annotations for SCN-* IDs ──────────────────────
python3 - <<'PYEOF'
import re, yaml
from pathlib import Path

registry_path = Path("tests/registry.yaml")
test_src = Path("src/test/java")

with open(registry_path) as f:
    data = yaml.safe_load(f)
scenarios = data.get("scenarios") or {}

found_ids = set()
# Match @DisplayName("SCN-XXX-NNN: ...") — single or double quotes, with optional whitespace
pattern = re.compile(r'@DisplayName\s*\(\s*["\']+(SCN-[A-Z]+-\d+)[:\s]')
for java_file in test_src.rglob("*.java"):
    content = java_file.read_text(errors="ignore")
    for m in pattern.finditer(content):
        found_ids.add(m.group(1))

updated = 0
for scn_id, entry in scenarios.items():
    if entry.get("override_status"):
        continue
    new_status = "covered" if scn_id in found_ids else "untested"
    if entry["status"] != new_status:
        entry["status"] = new_status
        updated += 1

with open(registry_path, "w") as f:
    f.write("# Auto-generated by scripts/sync-registry.sh\n")
    f.write("# Edit scenario entries in tests/scenarios/<domain>.md only.\n")
    f.write("# Hand-edit only: notes, override_status.\n\n")
    yaml.dump({"scenarios": scenarios}, f, default_flow_style=False, sort_keys=True, allow_unicode=True)

covered = sum(1 for e in scenarios.values() if e["status"] == "covered")
print(f"[sync] Status updated for {updated} scenario(s). Covered: {covered}/{len(scenarios)}")
PYEOF

# ── Step 3: Parse PIT XML for mutation_kill_rate per domain ──────────────────
if [ -f "$PIT_XML" ]; then
python3 - <<'PYEOF'
import xml.etree.ElementTree as ET, yaml
from collections import defaultdict
from pathlib import Path

registry_path = Path("tests/registry.yaml")
pit_xml = Path("build/reports/pitest/mutations.xml")

with open(registry_path) as f:
    data = yaml.safe_load(f)
scenarios = data.get("scenarios") or {}

tree = ET.parse(pit_xml)
root = tree.getroot()

pkg_stats = defaultdict(lambda: {"killed": 0, "total": 0})
for m in root.findall("mutation"):
    cls = m.findtext("mutatedClass", "")
    parts = cls.split(".")
    if len(parts) >= 3:
        domain = parts[2]  # mn.tasky.<domain>.*
        pkg_stats[domain]["total"] += 1
        if m.get("status") == "KILLED":
            pkg_stats[domain]["killed"] += 1

domain_rates = {
    d: round(100 * s["killed"] / s["total"])
    for d, s in pkg_stats.items() if s["total"] > 0
}

for entry in scenarios.values():
    domain = entry.get("domain", "")
    if domain in domain_rates:
        entry["mutation_kill_rate"] = domain_rates[domain]

with open(registry_path, "w") as f:
    f.write("# Auto-generated by scripts/sync-registry.sh\n")
    f.write("# Edit scenario entries in tests/scenarios/<domain>.md only.\n")
    f.write("# Hand-edit only: notes, override_status.\n\n")
    yaml.dump({"scenarios": scenarios}, f, default_flow_style=False, sort_keys=True, allow_unicode=True)

print(f"[sync] mutation_kill_rate updated for: {sorted(domain_rates.keys())}")
PYEOF
else
    echo "[sync] No PIT report at $PIT_XML — skipping mutation_kill_rate update"
fi

echo "[sync] Done. Registry: tests/registry.yaml"
