#!/usr/bin/env bash
# sync-registry.sh
# Parses tests/scenarios/*.md for SCN-* entries, syncs tests/registry.yaml,
# cross-references @DisplayName annotations in test code to update status,
# and parses PIT XML to update mutation_kill_rate per domain.
#
# Usage: ./scripts/sync-registry.sh
# Run from the repository root.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

SCENARIOS_DIR="${ROOT_DIR}/tests/scenarios"
REGISTRY="${ROOT_DIR}/tests/registry.yaml"
TEST_RESULTS_DIR="${ROOT_DIR}/services/api/build/test-results/test"
PIT_XML="${ROOT_DIR}/services/api/build/reports/pitest/mutations.xml"

export SCENARIOS_DIR REGISTRY TEST_RESULTS_DIR PIT_XML

# ── Step 1: Parse scenario files and upsert registry ─────────────────────────
python3 - <<'PYEOF'
import re, sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("[sync] ERROR: pyyaml not installed. Run: pip3 install pyyaml", file=sys.stderr)
    sys.exit(1)

import os

scenarios_dir = Path(os.environ["SCENARIOS_DIR"])
registry_path = Path(os.environ["REGISTRY"])

# Load existing registry to preserve notes and override_status
existing = {}
if registry_path.exists():
    with open(registry_path) as f:
        data = yaml.safe_load(f) or {}
        existing = data.get("scenarios") or {}

scenarios = {}
parse_errors = []
duplicate_ids = []

VALID_RISKS = {"critical", "high", "medium", "low"}

for md_file in sorted(scenarios_dir.glob("*.md")):
    domain = md_file.stem
    if domain == "README":
        continue
    content = md_file.read_text()
    blocks = re.split(r'\n(?=## SCN-)', content)
    for block in blocks:
        # Detect SCN header presence before full parse — catches malformed blocks
        header_match = re.match(r'## (SCN-[A-Z]+\d*-\d+)', block)
        if not header_match:
            continue  # Not a scenario block (e.g., file header text)

        scn_id_candidate = header_match.group(1)

        m = re.match(
            r'## (SCN-[A-Z]+\d*-\d+)\n+\*\*Risk:\*\* (\w+)\n\*\*PRD:\*\* ([^\n]+)\n\*\*Title:\*\* ([^\n]+)',
            block
        )
        if not m:
            parse_errors.append(
                f"  MALFORMED block for {scn_id_candidate} in {md_file.name} "
                f"— check Risk/PRD/Title field order and formatting"
            )
            continue

        scn_id = m.group(1)
        risk = m.group(2).strip().lower()
        prd_ref = m.group(3).strip()
        title = m.group(4).strip()

        if risk not in VALID_RISKS:
            parse_errors.append(
                f"  INVALID risk '{risk}' for {scn_id} in {md_file.name} "
                f"— must be one of: {', '.join(sorted(VALID_RISKS))}"
            )
            continue

        if scn_id in scenarios:
            duplicate_ids.append(
                f"  DUPLICATE ID {scn_id} in {md_file.name} "
                f"(first seen in {scenarios[scn_id]['domain']}.md)"
            )
            continue  # Do not overwrite — first definition wins

        test_type = "domain-unit" if risk in ("critical", "high") else "medium-unit"
        if domain == "integration":
            test_type = "integration"

        prev = existing.get(scn_id) or {}
        scenarios[scn_id] = {
            "title": title,
            "domain": domain,
            "risk": risk,
            "prd_ref": prd_ref,
            "test_type": test_type,
            "status": prev.get("status", "untested"),
            "mutation_kill_rate": prev.get("mutation_kill_rate"),
            "mutation_kill_rate_updated_at": prev.get("mutation_kill_rate_updated_at"),
            "notes": prev.get("notes"),
            "override_status": prev.get("override_status"),
        }

# Report parse errors as warnings (stderr)
if parse_errors:
    print("[sync] WARNING: malformed scenario blocks found:", file=sys.stderr)
    for msg in parse_errors:
        print(msg, file=sys.stderr)

# Duplicate IDs are hard errors — exit non-zero so CI catches them immediately
if duplicate_ids:
    print("[sync] ERROR: duplicate scenario IDs found:", file=sys.stderr)
    for msg in duplicate_ids:
        print(msg, file=sys.stderr)
    print("[sync] Fix duplicates in tests/scenarios/ before proceeding.", file=sys.stderr)
    sys.exit(1)

registry_path.parent.mkdir(parents=True, exist_ok=True)
with open(registry_path, "w") as f:
    f.write("# Auto-generated by scripts/sync-registry.sh\n")
    f.write("# Edit scenario entries in tests/scenarios/<domain>.md only.\n")
    f.write("# Hand-edit only: notes, override_status.\n\n")
    yaml.dump({"scenarios": scenarios}, f, default_flow_style=False, sort_keys=True, allow_unicode=True)

print(f"[sync] Parsed {len(scenarios)} scenarios from {scenarios_dir}")
PYEOF

# ── Step 2: Scan surefire XML results for PASSING SCN-* tests ────────────────
# Reads build/test-results/test/TEST-*.xml — only testcase elements with no
# <failure> or <skipped> child are treated as covered. This means:
#   - @Disabled tests: skipped element present → not covered
#   - Commented-out tests: never appear in XML → not covered
#   - Failing tests: failure element present → not covered
#   - Tests that did not run (no test run yet): XML absent → warn, not covered
python3 - <<'PYEOF'
import re, sys, yaml
import xml.etree.ElementTree as ET
from pathlib import Path

import os

registry_path = Path(os.environ["REGISTRY"])
surefire_dir = Path(os.environ["TEST_RESULTS_DIR"])

with open(registry_path) as f:
    data = yaml.safe_load(f)
scenarios = data.get("scenarios") or {}

if not surefire_dir.exists():
    print("[sync] WARNING: no surefire results at build/test-results/test/ — "
          "run ./gradlew test first. Status not updated.", file=sys.stderr)
else:
    found_ids = set()
    # Match any SCN-* ID anywhere in the test name — handles multiple IDs in one @DisplayName
    # e.g. "SCN-AUTH-013 SCN-SMOKE-001: ..." picks up both IDs
    scn_anywhere = re.compile(r'\b(SCN-[A-Z]+-\d+)\b')

    for xml_file in surefire_dir.glob("TEST-*.xml"):
        try:
            tree = ET.parse(xml_file)
        except ET.ParseError as e:
            print(f"[sync] WARNING: could not parse {xml_file.name}: {e}", file=sys.stderr)
            continue

        for testcase in tree.findall(".//testcase"):
            name = testcase.get("name", "")
            # Skip failed tests
            if testcase.find("failure") is not None:
                continue
            # Skip skipped/disabled tests
            if testcase.find("skipped") is not None:
                continue
            for m in scn_anywhere.finditer(name):
                found_ids.add(m.group(1))

    updated = 0
    for scn_id, entry in scenarios.items():
        if entry.get("override_status"):
            continue
        new_status = "covered" if scn_id in found_ids else "untested"
        if entry["status"] != new_status:
            entry["status"] = new_status
            updated += 1

    with open(registry_path, "w") as f:
        f.write("# Auto-generated by scripts/sync-registry.sh\n")
        f.write("# Edit scenario entries in tests/scenarios/<domain>.md only.\n")
        f.write("# Hand-edit only: notes, override_status.\n\n")
        yaml.dump({"scenarios": scenarios}, f, default_flow_style=False, sort_keys=True, allow_unicode=True)

    covered = sum(1 for e in scenarios.values() if e["status"] == "covered")
    print(f"[sync] Status updated for {updated} scenario(s). Covered: {covered}/{len(scenarios)}")
PYEOF

# ── Step 3: Parse PIT XML for mutation_kill_rate per domain ──────────────────
if [ -f "$PIT_XML" ]; then
python3 - <<'PYEOF'
import xml.etree.ElementTree as ET, yaml
from collections import defaultdict
from pathlib import Path

import os

registry_path = Path(os.environ["REGISTRY"])
pit_xml = Path(os.environ["PIT_XML"])

with open(registry_path) as f:
    data = yaml.safe_load(f)
scenarios = data.get("scenarios") or {}

tree = ET.parse(pit_xml)
root = tree.getroot()

pkg_stats = defaultdict(lambda: {"killed": 0, "total": 0})
for m in root.findall("mutation"):
    cls = m.findtext("mutatedClass", "")
    parts = cls.split(".")
    if len(parts) >= 3:
        domain = parts[2]  # mn.tasky.<domain>.*
        pkg_stats[domain]["total"] += 1
        if m.get("status") == "KILLED":
            pkg_stats[domain]["killed"] += 1

domain_rates = {
    d: round(100 * s["killed"] / s["total"])
    for d, s in pkg_stats.items() if s["total"] > 0
}

from datetime import datetime, timezone

now_iso = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
for entry in scenarios.values():
    domain = entry.get("domain", "")
    if domain in domain_rates:
        entry["mutation_kill_rate"] = domain_rates[domain]
        entry["mutation_kill_rate_updated_at"] = now_iso

with open(registry_path, "w") as f:
    f.write("# Auto-generated by scripts/sync-registry.sh\n")
    f.write("# Edit scenario entries in tests/scenarios/<domain>.md only.\n")
    f.write("# Hand-edit only: notes, override_status.\n\n")
    yaml.dump({"scenarios": scenarios}, f, default_flow_style=False, sort_keys=True, allow_unicode=True)

print(f"[sync] mutation_kill_rate updated for: {sorted(domain_rates.keys())}")
PYEOF
else
    echo "[sync] No PIT report at $PIT_XML — skipping mutation_kill_rate update"
fi

echo "[sync] Done. Registry: ${REGISTRY}"
